POST http://localhost:8081/users
Content-Type: application/json

{
    "id": 3,
    "name": "Priya",
    "email": "priya@gmail.com"
}

PUT http://localhost:8081/users/3
Content-Type: application/json

{
    "name": "Priya Updated",
    "email": "priya.updated@gmail.com"
}
] Update User
PUT http://localhost:8081/users/3
Content-Type: application/json

{
    "id": 3,
    "name": "Priya Updated",
    "email": "priya.updated@gmail.com"
}

### DELETE - Delete User
DELETE http://localhost:8081/users/3

### GET - All Users
GET http://localhost:8081/users